/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { 
  Search, Sparkles, AlertCircle, Eye, ArrowRight, 
  HelpCircle, CheckCircle, Database, FileText 
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { SearchResult, RAGResponse } from '../types';

interface SemanticSearchProps {
  onSearch: (query: string, threshold: number, limit: number) => Promise<{ semantic: SearchResult[]; keyword: SearchResult[] }>;
  onGenerateRAG: (query: string, results: SearchResult[]) => Promise<RAGResponse>;
}

export default function SemanticSearch({ onSearch, onGenerateRAG }: SemanticSearchProps) {
  const [query, setQuery] = useState('');
  const [threshold, setThreshold] = useState(0.35);
  const [limit, setLimit] = useState(5);
  const [searching, setSearching] = useState(false);
  const [synthesizing, setSynthesizing] = useState(false);
  
  // Results
  const [semanticResults, setSemanticResults] = useState<SearchResult[] | null>(null);
  const [keywordResults, setKeywordResults] = useState<SearchResult[] | null>(null);
  const [ragResponse, setRagResponse] = useState<RAGResponse | null>(null);
  const [searchedQuery, setSearchedQuery] = useState('');

  const suggestedQueries = [
    'How does working from home work?',
    'Workplace hardware stipends',
    'How do we deploy our containerized apps?',
    'Workstation file encryption standards',
    'What is our brand design philosophy?',
    'What is the email for reporting laptop loss?'
  ];

  const handleSearchSubmit = async (searchStr: string) => {
    if (!searchStr.trim()) return;
    
    setSearching(true);
    setSynthesizing(true);
    setSearchedQuery(searchStr);
    
    try {
      const data = await onSearch(searchStr, threshold, limit);
      setSemanticResults(data.semantic);
      setKeywordResults(data.keyword);
      
      // If we have semantic matches, run RAG synthesis on those matches
      if (data.semantic && data.semantic.length > 0) {
        const rag = await onGenerateRAG(searchStr, data.semantic);
        setRagResponse(rag);
      } else {
        setRagResponse({
          answer: "No semantically matching documents found above the similarity threshold to synthesize an AI answer. Try lowering the 'Similarity Threshold' slider or adding relevant files to the repository.",
          sourcesUsed: []
        });
      }
    } catch (err) {
      console.error('Search flow failed:', err);
    } finally {
      setSearching(false);
      setSynthesizing(false);
    }
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    handleSearchSubmit(query);
  };

  return (
    <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm" id="semantic-search-root">
      <div className="border-b border-slate-100 pb-6 mb-6">
        <h2 className="text-lg font-bold text-slate-800 flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-indigo-600" />
          Semantic Search Engine & QA
        </h2>
        <p className="text-xs text-slate-500 mt-1">
          Perform concept-based searches & obtain citations generated by Gemini models
        </p>
      </div>

      {/* Suggested Queries */}
      <div className="mb-6">
        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2.5">Suggested Concepts to Test:</p>
        <div className="flex flex-wrap gap-2" id="suggested-queries-list">
          {suggestedQueries.map((item, idx) => (
            <button
              key={idx}
              id={`suggested-query-${idx}`}
              onClick={() => {
                setQuery(item);
                handleSearchSubmit(item);
              }}
              className="px-3.5 py-1.5 text-xs text-slate-600 bg-slate-50 border border-slate-200 hover:border-indigo-300 hover:bg-indigo-50/50 hover:text-indigo-700 rounded-full transition-all cursor-pointer text-left font-semibold"
            >
              {item}
            </button>
          ))}
        </div>
      </div>

      {/* Control panel for search */}
      <form onSubmit={handleFormSubmit} className="space-y-4">
        <div className="relative">
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search documents by meaning or ask a direct question..."
            className="w-full pl-12 pr-28 py-3 border border-slate-200 rounded-full focus:ring-2 focus:ring-indigo-100 focus:border-indigo-500 outline-none text-sm text-slate-800 bg-slate-50/50 font-medium placeholder-slate-400"
            required
            id="search-input-field"
          />
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
          <button
            type="submit"
            disabled={searching}
            id="search-submit-button"
            className="absolute right-2 top-1/2 -translate-y-1/2 px-4 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-xs rounded-full shadow-sm transition-colors cursor-pointer flex items-center gap-1.5 disabled:opacity-50"
          >
            {searching ? (
              <RefreshCw className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <>
                <Search className="w-3.5 h-3.5" />
                Analyze
              </>
            )}
          </button>
        </div>

        {/* Sliders / Filters collapsible section */}
        <div className="bg-slate-50/50 border border-slate-200 rounded-xl p-4 grid grid-cols-1 md:grid-cols-2 gap-6" id="search-parameters">
          <div>
            <div className="flex items-center justify-between text-xs font-semibold text-slate-500 mb-2">
              <span className="flex items-center gap-1">
                Relevance Threshold
                <HelpCircle className="w-3.5 h-3.5 text-slate-400" title="Minimum cosine similarity required to count as a match" />
              </span>
              <span className="font-mono text-indigo-600">{(threshold * 100).toFixed(0)}%</span>
            </div>
            <input
              type="range"
              min="0.1"
              max="0.9"
              step="0.05"
              value={threshold}
              onChange={(e) => setThreshold(parseFloat(e.target.value))}
              className="w-full accent-indigo-600 cursor-pointer h-1.5 bg-slate-200 rounded-full appearance-none"
              id="threshold-slider"
            />
            <p className="text-[10px] text-slate-400 mt-1">
              Higher means matches are more precise; lower returns broader matches.
            </p>
          </div>

          <div>
            <div className="flex items-center justify-between text-xs font-semibold text-slate-500 mb-2">
              <span>Maximum Context Limit</span>
              <span className="font-mono text-indigo-600">{limit} Docs</span>
            </div>
            <div className="flex gap-2">
              {[3, 5, 8, 10].map((v) => (
                <button
                  type="button"
                  key={v}
                  id={`limit-btn-${v}`}
                  onClick={() => setLimit(v)}
                  className={`flex-1 py-1 text-xs font-semibold rounded-lg border transition-all cursor-pointer ${
                    limit === v 
                      ? 'border-indigo-200 bg-indigo-50 text-indigo-600' 
                      : 'border-slate-200 bg-white text-slate-500 hover:bg-slate-50'
                  }`}
                >
                  {v}
                </button>
              ))}
            </div>
            <p className="text-[10px] text-slate-400 mt-1">
              Maximum documents to feed into the Gemini RAG summarizer context.
            </p>
          </div>
        </div>
      </form>

      {/* Comparative Search results displays */}
      <AnimatePresence>
        {searchedQuery && (
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            className="mt-8 space-y-8"
            id="results-container"
          >
            {/* 1. RAG Answer */}
            <div className="bg-indigo-50/20 border border-indigo-100 rounded-xl p-5" id="rag-response-box">
              <div className="flex items-center justify-between gap-2 border-b border-indigo-100/30 pb-3 mb-3">
                <h3 className="font-bold text-slate-800 text-xs uppercase tracking-wider flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-indigo-600 animate-pulse" />
                  Grounded AI Answer (Gemini RAG)
                </h3>
                <span className="px-2.5 py-0.5 text-[9px] font-bold text-indigo-700 bg-indigo-100 rounded border border-indigo-200 uppercase tracking-wider">
                  Verified Synthesis
                </span>
              </div>
              {synthesizing ? (
                <div className="space-y-3 py-2">
                  <div className="h-4 bg-indigo-100/50 rounded-md animate-pulse w-3/4" />
                  <div className="h-4 bg-indigo-100/50 rounded-md animate-pulse w-5/6" />
                  <div className="h-4 bg-indigo-100/50 rounded-md animate-pulse w-2/3" />
                </div>
              ) : ragResponse ? (
                <div>
                  <p className="text-slate-700 text-sm font-sans leading-relaxed whitespace-pre-wrap italic">
                    "{ragResponse.answer}"
                  </p>
                  {ragResponse.sourcesUsed.length > 0 && (
                    <div className="mt-4 pt-3 border-t border-indigo-100/30">
                      <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">Sources Referenced:</p>
                      <div className="flex flex-wrap gap-1.5">
                        {ragResponse.sourcesUsed.map((source, idx) => (
                          <span
                            key={idx}
                            className="px-2 py-0.5 text-[10px] font-semibold text-indigo-700 bg-indigo-100/60 rounded flex items-center gap-1 border border-indigo-200"
                          >
                            <FileText className="w-3 h-3" />
                            {source}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              ) : null}
            </div>

            {/* Results Title with query highlighted */}
            <div className="p-4 border-b border-slate-100 bg-slate-50/30 rounded-lg flex items-center justify-between">
              <h2 className="text-sm font-bold text-slate-800 uppercase tracking-wider">
                Results for <span className="italic text-indigo-600">"{searchedQuery}"</span>
              </h2>
            </div>

            {/* 2. Comparative Sidebar grids */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6" id="comparative-grids">
              {/* Semantic Matches */}
              <div className="space-y-4" id="semantic-column">
                <div className="flex items-center justify-between border-b border-slate-200 pb-2">
                  <h4 className="text-xs font-bold text-slate-500 uppercase tracking-widest flex items-center gap-1.5">
                    <Database className="w-4 h-4 text-indigo-600" />
                    Semantic Embeddings
                  </h4>
                  <span className="text-[10px] text-slate-400 font-bold font-mono">
                    gemini-embedding-2
                  </span>
                </div>

                {searching ? (
                  <div className="space-y-4">
                    {[1, 2].map((i) => (
                      <div key={i} className="animate-pulse border border-slate-200 rounded-xl p-5 h-32 bg-slate-50/30" />
                    ))}
                  </div>
                ) : semanticResults === null ? (
                  <p className="text-xs text-slate-400 italic">No search executed.</p>
                ) : semanticResults.length === 0 ? (
                  <div className="p-8 text-center border border-dashed border-slate-200 rounded-xl bg-slate-50/30">
                    <AlertCircle className="w-6 h-6 text-slate-300 mx-auto mb-2" />
                    <p className="text-xs font-bold text-slate-500">No Semantic Matches</p>
                    <p className="text-[10px] text-slate-400 mt-1">None surpassed {Math.round(threshold * 100)}% similarity score.</p>
                  </div>
                ) : (
                  <div className="space-y-4" id="semantic-results-list">
                    {semanticResults.map((res) => (
                      <div
                        key={res.document.id}
                        id={`semantic-result-${res.document.id}`}
                        className="group p-5 rounded-xl border border-indigo-100 bg-indigo-50/20 hover:border-indigo-300 hover:bg-indigo-50/35 transition-colors shadow-sm"
                      >
                        <div className="flex justify-between items-start mb-2">
                          <div className="flex items-center gap-2">
                            <span className="px-2 py-0.5 bg-indigo-100 text-indigo-700 text-[10px] font-bold rounded uppercase tracking-wider">
                              {Math.round(res.similarityScore * 100)}% Match
                            </span>
                            <h4 className="font-bold text-slate-800 text-sm group-hover:text-indigo-700 transition-colors">
                              {res.document.title}
                            </h4>
                          </div>
                        </div>
                        <p className="text-xs text-slate-600 leading-relaxed font-sans mt-2 line-clamp-3">
                          {res.document.content}
                        </p>
                        <div className="flex gap-4 mt-3">
                          <div className="flex items-center gap-1.5">
                            <div className="w-2 h-2 bg-indigo-400 rounded-full"></div>
                            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{res.document.category}</span>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Keyword Matches */}
              <div className="space-y-4" id="keyword-column">
                <div className="flex items-center justify-between border-b border-slate-200 pb-2">
                  <h4 className="text-xs font-bold text-slate-500 uppercase tracking-widest flex items-center gap-1.5">
                    <Search className="w-4 h-4 text-slate-400" />
                    Standard Keyword
                  </h4>
                  <span className="text-[10px] text-slate-400 font-bold font-mono">
                    literal match
                  </span>
                </div>

                {searching ? (
                  <div className="space-y-4">
                    {[1, 2].map((i) => (
                      <div key={i} className="animate-pulse border border-slate-200 rounded-xl p-5 h-32 bg-slate-50/30" />
                    ))}
                  </div>
                ) : keywordResults === null ? (
                  <p className="text-xs text-slate-400 italic">No search executed.</p>
                ) : keywordResults.length === 0 ? (
                  <div className="p-8 text-center border border-dashed border-slate-200 rounded-xl bg-slate-50/30">
                    <AlertCircle className="w-6 h-6 text-slate-300 mx-auto mb-2" />
                    <p className="text-xs font-bold text-slate-500">No Keyword Matches</p>
                    <p className="text-[10px] text-slate-400 mt-1">Literal text contains could not find "{searchedQuery}".</p>
                  </div>
                ) : (
                  <div className="space-y-4" id="keyword-results-list">
                    {keywordResults.map((res) => (
                      <div
                        key={res.document.id}
                        id={`keyword-result-${res.document.id}`}
                        className="group p-5 rounded-xl border border-slate-200 bg-white hover:border-slate-300 transition-colors shadow-sm"
                      >
                        <div className="flex justify-between items-start mb-2">
                          <div className="flex items-center gap-2">
                            <span className="px-2 py-0.5 bg-slate-100 text-slate-600 text-[10px] font-bold rounded uppercase tracking-wider">
                              Keyword Hit
                            </span>
                            <h4 className="font-bold text-slate-800 text-sm group-hover:text-slate-900 transition-colors">
                              {res.document.title}
                            </h4>
                          </div>
                        </div>
                        <p className="text-xs text-slate-600 leading-relaxed font-sans mt-2 line-clamp-3">
                          {res.document.content}
                        </p>
                        <div className="flex gap-4 mt-3">
                          <div className="flex items-center gap-1.5">
                            <div className="w-2 h-2 bg-slate-300 rounded-full"></div>
                            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{res.document.category}</span>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// Inline loading spinner helper
function RefreshCw(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={props.className}
    >
      <path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
      <path d="M3 3v5h5" />
      <path d="M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16" />
      <path d="M16 16h5v5" />
    </svg>
  );
}
